"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[fill]
symbol = ' '

[directory]
truncation_length = 2
truncation_symbol = '…/'
truncate_to_repo = false

[character]
success_symbol = "[→ ](bold green)"
error_symbol = "[✘ ](bold red)"
