[general]
live_config_reload = true

[window]
opacity = 0.90
dynamic_padding = false
# decorations = "None"

[window.padding]
x = 22
y = 18

[font]
size = 14.0
normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"
# normal.family = "MonoLisa Nerd Font Mono"
# bold.family = "MonoLisa Nerd Font Mono"
# italic.family = "MonoLisa Nerd Font Mono"
# bold_italic.family = "MonoLisa Nerd Font Mono"


# [terminal.shell]
# program = "tmux"

# [terminal.shell]
# program = "zsh"
# args = [
#     "-c",
#     '[[ -z "$TMUX" ]] && exec tmux new-session -A -s main || exec zsh',
# ]

# [terminal.shell]
# program = "zsh"
# args = [
#     "-c",
#     "[[ -z \\\"$TMUX\\\" ]] && exec tmux new-session -A -s main || exec zsh",
# ]
# [terminal.shell]
# program = "zsh"
# args = [
#     "-c",
#     'if [ -z "$TMUX" ]; then exec tmux new-session -A -s main; else exec zsh; fi',
# ]
