[general]
live_config_reload = true

[window]
opacity = 0.90
dynamic_padding = false
# decorations = "None"

[window.padding]
x = 22
y = 18

[font]
size = 14.0
normal.family = "MonoLisa Nerd Font Mono"
bold.family = "MonoLisa Nerd Font Mono"
italic.family = "MonoLisa Nerd Font Mono"
bold_italic.family = "MonoLisa Nerd Font Mono"
